server:
  servlet:
    context-path: /keycloak
  port: 5001

keycloak:
  realm: RealmSpringBoot
  auth-server-url: http://localhost:8080/auth
  resource: login
  principal-attribute: preferred_username
  public-client: true

spring:
  main:
    allow-bean-definition-overriding: true